apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
spec:
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.0
    - timeo=60
    - retrans=10
  capacity:
    storage: 10Gi
  nfs:
    server: 10.0.0.11
    path: "/shares/share-76bb-49e1-90b5-f4ddaecdb3f7"
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: nfs-hdd
